### ISSUE TITLE
benchmarkSQL使用中遇到的问题

### ISSUE THREAD

**Issue by marsapolo** [lealone/Lealone-Docs#4]
你好，又来请教了，
我们在使用benchmarkSQL的时候，遇到了新的问题
表结构能正常，插数据的时候报错了，您给看看吧
![image](https://user-images.githubusercontent.com/19219734/164143643-807a9395-f595-4158-8b7d-76f0537bff47.png)

下图是lealone端的错误提示
![image](https://user-images.githubusercontent.com/19219734/164143688-f909f03c-45d0-4f02-88a2-0783941e2085.png)

是executeBatch使用的不对吗

**Comment by codefollower** [comment]
benchmarkSQL 用了 VACCUM 这种 PostgreSQL 特有的语法访问 lealone 数据库肯定出错的。

**Comment by tianmaotalk** [comment]
> 

这是在数据加载的时候报错的，并没有 vacuum 这个东西，就是普通的preparedStatement，addbatch，在executebatch的报错了。
