### ISSUE TITLE
请问可以用什么数据库客户端连接数据库？

### ISSUE THREAD

**Issue by zhangyou1010** [lealone/Lealone-Docs#5]
请问可以用什么数据库客户端连接数据库？

**Comment by codefollower** [comment]
lealone 数据库自带数据库客户端
下载 [lealone-5.0.0.jar](https://github.com/lealone/Lealone-Docs/releases/download/lealone-docs-1.0.0/lealone-5.0.0.jar)

启动数据库：java -jar lealone-5.0.0.jar
启动客户端：java -jar lealone-5.0.0.jar -client

运行环境需要 jdk 1.8+

**Comment by zhangyou1010** [comment]
这是命令行client吧？ 支持gui client吗？

**Comment by codefollower** [comment]
[Lealone-OpsCenter](https://github.com/lealone/Lealone-OpsCenter#readme)
只有这个 web ui，改编自 h2 数据库。其他 ui 客户端就没有了。

**Comment by zoujiegogogo** [comment]
现在你可以看看最新的连接数据库的[教程](https://github.com/lealone/Lealone-Examples/issues/23)
