### ISSUE TITLE
ubuntu 编译出错

### ISSUE THREAD

**Issue by jhkwei** [lealone/Lealone-Docs#8]
想找一项目学习一下 java ,没有想到编译出错了
mvn clean package assembly:assembly -Dmaven.test.skip=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] lealone database project
[INFO] lealone-common
[INFO] lealone-net
[INFO] lealone-client
[INFO] lealone-db
[INFO] lealone-sql
[INFO] lealone-server
[INFO] lealone-aote
[INFO] lealone-aose
[INFO] lealone-orm
[INFO] lealone-web
[INFO] lealone-main
[INFO] lealone-test
[INFO] lealone-dist
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building lealone database project 5.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ lealone ---
[INFO] 
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) > generate-sources @ lealone >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) < generate-sources @ lealone <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ lealone ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building lealone-common 5.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ lealone-common ---
[INFO] Deleting /home/shenwei/test/lealone/lealone-common/target
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ lealone-common ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ lealone-common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 231 source files to /home/shenwei/test/lealone/lealone-common/target/classes
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Skipping lealone database project
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] lealone database project ........................... SUCCESS [  0.284 s]
[INFO] lealone-common ..................................... FAILURE [  0.393 s]
[INFO] lealone-net ........................................ SKIPPED
[INFO] lealone-client ..................................... SKIPPED
[INFO] lealone-db ......................................... SKIPPED
[INFO] lealone-sql ........................................ SKIPPED
[INFO] lealone-server ..................................... SKIPPED
[INFO] lealone-aote ....................................... SKIPPED
[INFO] lealone-aose ....................................... SKIPPED
[INFO] lealone-orm ........................................ SKIPPED
[INFO] lealone-web ........................................ SKIPPED
[INFO] lealone-main ....................................... SKIPPED
[INFO] lealone-test ....................................... SKIPPED
[INFO] lealone-dist ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.885 s
[INFO] Finished at: 2022-09-06T17:42:41-07:00
[INFO] Final Memory: 13M/221M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project lealone-common: Fatal error compiling: 无效的标记: --release -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :lealone-common

**Comment by codefollower** [comment]
jdk 8 不支持 --release 参数，换个新的 jdk，比如 jdk 17
